server:
  port: 8080


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api-admin
          uri: http://localhost:8000/
          predicates:
            - Path=/admin/**
        - id: api-internal
          uri: http://localhost:8100/
          predicates:
            - Path=/internal/**

